import argparse
import os
import sys
import time
import glob
import subprocess

from . import compile_source, TuaSyntaxError, TuaTypeError, __version__

banner = r"""
  _/_/_/_/_/  _/    _/    _/_/
     _/      _/    _/  _/    _/
    _/      _/    _/  _/_/_/_/
   _/       _/  _/  _/     _/
  _/         _/    _/     _/     lua, with types.
"""


class Palette:
    def __init__(self, enabled):
        self.enabled = enabled

    def _wrap(self, code, text):
        return f"\033[{code}m{text}\033[0m" if self.enabled else text

    def red(self, t): return self._wrap("31", t)
    def green(self, t): return self._wrap("32", t)
    def yellow(self, t): return self._wrap("33", t)
    def cyan(self, t): return self._wrap("36", t)
    def bold(self, t): return self._wrap("1", t)
    def dim(self, t): return self._wrap("2", t)


def _color_enabled(args):
    if args.no_color or os.environ.get("NO_COLOR"):
        return False
    return sys.stdout.isatty()


def find_tua_files(path):
    if os.path.isfile(path):
        return [path]
    if os.path.isdir(path):
        return sorted(glob.glob(os.path.join(path, "**", "*.tua"), recursive=True))
    return []


def out_path_for(src, src_root, out_dir):
    if out_dir is None:
        base, _ = os.path.splitext(src)
        return base + ".lua"
    rel = os.path.relpath(src, src_root) if os.path.isdir(src_root) else os.path.basename(src)
    base, _ = os.path.splitext(rel)
    return os.path.join(out_dir, base + ".lua")


def compile_one(src, out_dir, src_root, pal, type_check, quiet):
    dest = out_path_for(src, src_root, out_dir)
    with open(src, "r", encoding="utf-8") as f:
        source = f.read()
    header = f"-- generated by tua {__version__} -- do not edit by hand, edit {os.path.basename(src)} instead"
    try:
        lua_code = compile_source(source, filename=src, type_check=type_check, header_comment=header)
    except TuaSyntaxError as e:
        print(pal.red("syntax error ") + str(e), file=sys.stderr)
        return False
    except TuaTypeError as e:
        print(pal.red(f"type error(s) in {src}:"), file=sys.stderr)
        for line, msg in sorted(set(e.errors)):
            print(f"  {pal.yellow(f'{src}:{line}')}  {msg}", file=sys.stderr)
        return False

    os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
    with open(dest, "w", encoding="utf-8") as f:
        f.write(lua_code)
    if not quiet:
        print(f"  {pal.green('✓')} {src} {pal.dim('->')} {dest}")
    return True


def cmd_build(args, pal):
    files = find_tua_files(args.input)
    if not files:
        print(pal.red(f"no .tua files found at {args.input!r}"), file=sys.stderr)
        return 1
    src_root = args.input
    ok = True
    start = time.time()
    for f in files:
        if not compile_one(f, args.out, src_root, pal, not args.no_check, args.quiet):
            ok = False
    elapsed = (time.time() - start) * 1000
    if ok and not args.quiet:
        n = len(files)
        print(pal.bold(pal.green(f"built {n} file{'s' if n != 1 else ''} in {elapsed:.0f}ms")))
    return 0 if ok else 1


def cmd_check(args, pal):
    files = find_tua_files(args.input)
    if not files:
        print(pal.red(f"no .tua files found at {args.input!r}"), file=sys.stderr)
        return 1
    
    ok = True

    for src in files:
        with open(src, "r", encoding="utf-8") as f:
            source = f.read()
        try:
            compile_source(source, filename=src, type_check=True)
        except TuaSyntaxError as e:
            print(pal.red("syntax error ") + str(e), file=sys.stderr)
            ok = False
        except TuaTypeError as e:
            print(pal.red(f"type error(s) in {src}:"), file=sys.stderr)
            for line, msg in sorted(set(e.errors)):
                print(f"  {pal.yellow(f'{src}:{line}')}  {msg}", file=sys.stderr)
            ok = False
        else:
            if not args.quiet:
                print(f"  {pal.green('✓')} {src}")
    if ok and not args.quiet:
        print(pal.bold(pal.green("no type errors")))
    return 0 if ok else 1


def cmd_run(args, pal):
    if not os.path.isfile(args.input):
        print(pal.red(f"{args.input} is not a file"), file=sys.stderr)
        return 1
    with open(args.input, "r", encoding="utf-8") as f:
        source = f.read()
    try:
        lua_code = compile_source(source, filename=args.input, type_check=not args.no_check)
    except TuaSyntaxError as e:
        print(pal.red("syntax error ") + str(e), file=sys.stderr)
        return  1
    except TuaTypeError as e:
        print(pal.red(f"type error(s) in {args.input}:"), file=sys.stderr)
        for line, msg in sorted(set(e.errors)):
            print(f"  {pal.yellow(f'{args.input}:{line}')}  {msg}", file=sys.stderr)
        return 1

    tmp_dest = os.path.splitext(args.input)[0] + ".tua.tmp.lua"
    with open(tmp_dest, "w", encoding="utf-8") as f:
        f.write(lua_code)
    try:
        lua_bin = args.lua or "lua"
        proc = subprocess.run([lua_bin, tmp_dest] + args.args)
        return proc.returncode
    except FileNotFoundError:
        print(pal.red(f"couldn't find a lua interpreter ({lua_bin!r}) on PATH"), file=sys.stderr)
        print(pal.dim("pass --lua <path> to point at one, e.g. --lua lua5.1"), file=sys.stderr)
        return 1
    finally:
        if not args.keep_temp:
            try:
                os.remove(tmp_dest)
            except OSError:
                pass


def cmd_watch(args, pal):
    print(pal.cyan(f"watching {args.input} for changes... (ctrl+c to stop)"))
    mtimes = {}
    try:
        while True:
            files = find_tua_files(args.input)
            changed = False
            for f in files:
                m = os.path.getmtime(f)
                if mtimes.get(f) != m:
                    mtimes[f] = m
                    changed = True
                    compile_one(f, args.out, args.input, pal, not args.no_check, args.quiet)
            if changed:
                print(pal.dim(f"  waiting for changes... [{time.strftime('%H:%M:%S')}]"))
            time.sleep(0.4)
    except KeyboardInterrupt:
        print(f"stopped watching {args.input}")
        return 0


def build_argparser():
    p = argparse.ArgumentParser(
        prog="tua",
        description="tua - a small, strictly typed language that compiles to plain Lua.",
    )
    p.add_argument("--version", action="version", version=f"tua {__version__}")
    p.add_argument("--no-color", action="store_true", help="disable colored output")
    sub = p.add_subparsers(dest="command")

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("input", help="a .tua file or a directory of .tua files")
    common.add_argument("--no-check", action="store_true", help="skip the static type checker")
    common.add_argument("-q", "--quiet", action="store_true", help="only print errors")

    b = sub.add_parser("build", parents=[common], help="compile .tua file(s) to .lua")
    b.add_argument("-o", "--out", default=None, help="output directory (default: next to the source)")

    c = sub.add_parser("check", parents=[common], help="type-check without writing any output")

    r = sub.add_parser(
        "run", parents=[common],
        help="compile and immediately run with a lua interpreter",
        epilog="pass arguments to the script itself after a literal '--', e.g. tua run game.tua -- --debug",
    )
    r.add_argument("--lua", default=None, help="path to the lua interpreter to use (default: 'lua')")
    r.add_argument("--keep-temp", action="store_true", help="keep the generated .lua file around")

    w = sub.add_parser("watch", parents=[common], help="rebuild automatically when files change")
    w.add_argument("-o", "--out", default=None, help="output directory (default: next to the source)")

    return p


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]

    # pull şt over
    script_args = []
    if "--" in argv:
        idx = argv.index("--")
        script_args = argv[idx + 1:]
        argv = argv[:idx]

    parser = build_argparser()
    args = parser.parse_args(argv)
    args.args = script_args
    pal = Palette(_color_enabled(args))

    if not args.command:
        print(pal.cyan(banner))
        parser.print_help()
        return 0

    if args.command == "build":
        return cmd_build(args, pal)
    if args.command == "check":
        return cmd_check(args, pal)
    if args.command == "run":
        return cmd_run(args, pal)
    if args.command == "watch":
        return cmd_watch(args, pal)

    parser.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
